name: Prompt Bot

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: read

jobs:
  run-prompt:
    if: contains(github.event.comment.body, '/prompt')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Call OpenAI (Responses API)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROMPT: ${{ github.event.comment.body }}
        run: |
          echo "Prompt: $PROMPT"
          RESP=$(curl -s https://api.openai.com/v1/responses \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"model\":\"gpt-4.1-mini\",\"input\":\"$PROMPT\"}")
          echo "$RESP" > response.json
          node -e "const r=require('./response.json'); console.log('\nModel output preview:\n', r.output_text)"

      - name: Write output to app/page.tsx
        shell: bash
        run: |
          set -e
          const fs=require('fs');
          const r=require('./response.json');
          const text=r.output_text || (r.output && r.output[0] && r.output[0].content && r.output[0].content[0].text) || '';
          if (!text) { console.error('No output_text found in response.json'); process.exit(1); }
          fs.writeFileSync('app/page.tsx', text);
          console.log(`Wrote app/page.tsx with ${text.length} chars`);

      - name: Commit & push changes
        shell: bash
        run: |
          git config user.name "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          git add app/page.tsx
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "AI bot: update homepage"
            git push
          fi
