name: AI Prompt Bot

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Prompt to send to ChatGPT"
        required: true
  repository_dispatch:
    types: [chatgpt_task]

permissions:
  contents: write

jobs:
  run-prompt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve prompt from event or manual input
        id: p
        run: |
          set -e
          if [ -n "${{ github.event.client_payload.prompt }}" ]; then
            echo "prompt=${{ github.event.client_payload.prompt }}" >> $GITHUB_OUTPUT
          else
            echo "prompt=${{ inputs.prompt }}" >> $GITHUB_OUTPUT
          fi

      - name: Call OpenAI (Responses API)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROMPT: ${{ steps.p.outputs.prompt }}
        run: |
          set -e
          echo "Prompt: $PROMPT"
          RESP=$(curl -sS https://api.openai.com/v1/responses \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"model\":\"gpt-4.1-mini\",\"input\": \"$PROMPT\"}")
          echo "$RESP" > response.json
          # print text result
          node -e "const r=require('./response.json'); console.log(r.output_text||JSON.stringify(r,null,2));"
